#Heatmap After Lefse
#Xin Zhou
#Load Library

library("phyloseq")
library("ggplot2")
library("scales")
library("grid")
library("ape")
library("plyr")

#Load the list generated by Lefse
SalivaLefse <- c("OTU_131", "OTU_34", "OTU_36", "OTU_181", "OTU_153",
                 "OTU_177", "OTU_61", "OTU_399", "OTU_168", "OTU_157",
                 "OTU_30", "OTU_208", "OTU_56", "OTU_141", "OTU_469",
                 "OTU_327", "OTU_35", "OTU_222", "OTU_338", "OTU_387", 
                 "OTU_169", "OTU_503", "OTU_319", "OTU_108", "OTU_417", 
                 "OTU_31", "OTU_190","OTU_464", "OTU_238", "OTU_293", "OTU_8")
SalivaLefse=rev(SalivaLefse)
Strain <- c("aa", "ab", "ac", "ad", "ae", 
           "af", "ag", "ah", "ai", "aj", 
           "ak", "al", "am", "an", "ao",
           "ap", "aq", "ar", "as", "at",
           "au", "av", "aw", "ax", "ay",
           "az", "ba", "bb", "bc", "bd", "be")

#StrainN <- c(1:31)
SalivaMerge=cbind(SalivaLefse,Strain)

#import file 
OTUTABLE=read.csv("~/Dropbox/Weinstock Lab/ZXE/ZXE2/Sequence Result/OTU95/otu_table.csv", header=T, sep=",", row.names=1)
TAXTABLE=read.csv("~/Dropbox/Weinstock Lab/ZXE/ZXE2/Sequence Result/OTU95/tax.csv", header=T, sep=",", row.names=1)
SAMPLE=read.csv("~/Dropbox/Weinstock Lab/ZXE/ZXE2/SampleID.csv", header=T, sep=",", row.names=1)
TREE=read_tree("~/Dropbox/Weinstock Lab/ZXE/ZXE2/Sequence Result/OTU95/Physeq_Tree")

#Subset samples 
otu=OTUTABLE[SalivaLefse,]
tax=TAXTABLE[SalivaLefse,]


#Convert to Phyloseq Format
otumat=as.matrix(otu)
taxmat=as.data.frame(tax)
taxmat$species=paste(taxmat$genus, row.names(taxmat), sep="|")

taxmat=merge(SalivaMerge,taxmat, by.y="row.names", by.x="SalivaLefse")
row.names(taxmat)=taxmat[,1]
taxmat=taxmat[,-1]
taxmat=as.matrix(taxmat)


OTU=otu_table(otumat,taxa_are_rows=TRUE)
TAX=tax_table(taxmat)
map1=sample_data(SAMPLE)

physeq=phyloseq(OTU,TAX,map1,TREE)

physeqsaliva=subset_samples(physeq, site=="saliva")

plot_tree(physeqsaliva, color="sampletype", label.tips = "species")
plot_heatmap(physeqsaliva,sample.order="sampletype",taxa.order="Strain")


StoolLefse <- c("OTU_2", "OTU_78", "OTU_126", "OTU_490", "OTU_513", 
                "OTU_427", "OTU_529", "OTU_206", "OTU_316", "OTU_447", 
                "OTU_334", "OTU_442", "OTU_315", "OTU_380", "OTU_482", 
                "OTU_472", "OTU_203", "OTU_331", "OTU_525", "OTU_480", 
                "OTU_416", "OTU_213", "OTU_272", "OTU_500", "OTU_33", 
                "OTU_489", "OTU_454", "OTU_201", "OTU_227", "OTU_105", 
                "OTU_103", "OTU_230", "OTU_183", "OTU_110", "OTU_159", 
                "OTU_99", "OTU_28")
StoolLefse=rev(StoolLefse)
Strain <- c("aa", "ab", "ac", "ad", "ae", 
            "af", "ag", "ah", "ai", "aj", 
            "ak", "al", "am", "an", "ao",
            "ap", "aq", "ar", "as", "at",
            "au", "av", "aw", "ax", "ay",
            "az", "ba", "bb", "bc", "bd", 
            "be", "bf", "bg", "bh", "bi",
            "bj", "bk")

StoolMerge=cbind(StoolLefse,Strain)
otu=OTUTABLE[StoolLefse,]
tax=TAXTABLE[StoolLefse,]


#Convert to Phyloseq Format
otumat=as.matrix(otu)
taxmat=as.data.frame(tax)
taxmat$species=paste(taxmat$genus, row.names(taxmat), sep="|")

taxmat=merge(StoolMerge,taxmat, by.x="StoolLefse", by.y="row.names")
row.names(taxmat)=taxmat[,1]
taxmat=taxmat[,-1]
taxmat=as.matrix(taxmat)


OTU=otu_table(otumat,taxa_are_rows=TRUE)
TAX=tax_table(taxmat)
map1=sample_data(SAMPLE)

physeq=phyloseq(OTU,TAX,map1,TREE)

physeqstool=subset_samples(physeq, site=="stool")

plot_tree(physeqstool, color="sampletype", label.tips = "species")
plot_heatmap(physeqstool,sample.order="sampletype",taxa.order="Strain")

